apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespaces
  - ../inference
  - ../mcp
  - ../agents

commonLabels:
  app.kubernetes.io/part-of: hermes-family-agents
  managed-by: kustomize